baseURL: https://nenadlazic.github.io/
theme: aafu
languageCode: en-us
build:
  writeStats: true
params:
  title: Nenad Lazić
  author: Nenad Lazić
  description: Software Engineer — Portfolio, Blog & Contact
  keywords: [Nenad, Lazic, Lazić, CV, Portfolio, Senior Software Engineer, Technical Lead, Blog, Java, C, C++, Streaming, DTV, Android, AI]
  copyright: >-
    powered by [hugo](https://gohugo.io/) & deployed on
    [GitHub Pages](https://pages.github.com/)
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: false
  favicons:
    use: true
    metas: |2-
              <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
              <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
              <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
              <link rel="manifest" href="site.webmanifest">
              <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
              <link rel="shortcut icon" href="favicon.ico">

  profile:
    name: "Nenad Lazić"
    tagline: Software Engineer
    location: "Belgrade, Serbia"
    photo: profile.jpg
  social:
    title: Links
    list:
      - icon: fab fa-linkedin-in
        url: "https://www.linkedin.com/in/nenad-lazic-7110a310a/"
        title: LinkedIn
      - icon: fab fa-github
        url: "https://github.com/nenadlazic"
        title: GitHub
      - icon: fab fa-stack-overflow
        url: "https://stackoverflow.com/users/7375893/nenad-lazic"
        title: StackOverflow
      - icon: fab fa-twitter
        url: "https://x.com/nlazic993"
        title: Twitter
      - icon: fab fa-instagram
        url: 'https://www.instagram.com/nlazic993/'
        title: Instagram
  showInAccordion:
    - item: aboutme
      expand: true
    - item: experience
    - item: education
    - item: services
    - item: project
    - item: skill
    - item: hobby
  aboutme:
    title: About Me
    icon: fas fa-user-tie
    description: Senior Software Engineer and Technical Lead with ~10 years of experience. Demonstrates proficiency in developing diverse projects across both client and backend systems, including system design and architectural planning. Possesses extensive expertise in technologies including C, C++, Java, Spring Boot, Kotlin, Python, Docker, Kubernetes, Android, among others. Consistently applies out-of-the-box thinking to solve complex problems, underpinned by a strong, goal-oriented approach. Effective organization and prioritization are central to leadership in ensuring the successful delivery of high-quality software projects from idea to launch.
  experience:
    title: Experiences
    icon: fas fa-briefcase
    list:
      - position: Software Engineer | Technical lead
        dates: 01/2022 - *Present*
        url: https://tyllo.net/
        company: Tyllo (UnitedCloud)
        details: |1-
          - Worked on backend solutions for media processing (transcoding, streaming, content protection), while leading a team of 10 engineers and designing architecture solutions across projects.
      - position: Software Engineer
        dates: 07/2020 - 01/2022
        url: "https://www.iwedia.com/"
        company: RT-RK (iWedia), Belgrade, Serbia
        details: |1-
          - Led and contributed to R&D of digital TV systems within iWedia, driving innovation and mentoring new team members.
      - position: Software Engineer
        dates: 07/2018 - 07/2020
        url: "https://www.bouyguestelecom.fr/"
        company: Bouygues telecom, Paris, France
        details: |1-
          - Collaborated with clients on feature planning and development, while maintaining a digital TV platform in production on over 3M devices.
      - position: Embedded Software Engineer
        dates: 09/2015 - 07/2018
        url: "https://www.rt-rk.com/"
        company: RT-RK, Belgrade, Serbia
        details: |1-
          - Worked on DTV middleware and Android UI solutions. Participated in all phases of agile development.
  education:
    title: Education
    icon: fas fa-graduation-cap
    list:
      - degree: M.S. in Computer Science
        college: Faculty of Mathematics, University of Belgrade
        dates: 2015 - 2018
        thesis_title: "Remote control of intelligent robots using android devices."
        thesis_url: "#"
      - degree: B.S. in Computer Science
        college: Faculty of Mathematics, University of Belgrade
        dates: 2012 - 2015
  services:
    title: Services
    icon: fas fa-laptop-code
    list:
      - title: Custom software engineering
        url: "#"
        description: Design and development of tailored software solutions — from backend systems in Java and C++, to full-featured client applications. Focused on building reliable, scalable, and maintainable applications aligned with your business needs.
      - title: Solution architecture & system design
        url: "#"
        description: Architecting complex distributed systems with an emphasis on performance, resilience, and long-term scalability. I help teams structure their systems using modern practices like event-driven design, clean architecture, and cloud-native infrastructure.
      - title: Media processing expertise
        url: "#"
        description: Extensive knowledge of video processing pipelines, including transcoding, packaging, and adaptive streaming (DVB/HLS/DASH). I help design and optimize media workflows using FFmpeg, integrate content protection through DRM and CAS systems, and support delivery across secure and scalable infrastructures.
  project:
    title: Projects
    icon: fas fa-code-branch
    list:
      - title: Project 1
        url: "#"
        description: project description
      - title: Project 2
        url: "#"
        description: project description
      - title: Project 3
        url: "#"
        description: project description
      - title: Project 4
        url: "#"
        description: project description
  skill:
    title: Skills
    panelId: skill-panel
    icon: fas fa-cogs
    list:
      - skill: "C/C++, Java, Spring Boot,  Vault, Keycloak, Kubernetes, GNU Linux, Jenkins, Docker, Kubernetes, Hibernate, OAuth, Kafka, Redis, Liquibase, PostgreSql, Prometheus, Grafana"
        skillrating: 100
      - skill: Kotlin, Python, Android, MySql, AWS
        skillrating: 90
      - skill: HTML,CSS, Bootstrap, JS, Vue.js
        skillrating: 65
  hobby:
    title: Hobbies
    icon: fas fa-heart
    list:
      - hobby: Basketball
      - hobby: Cars & mechanics
      - hobby: Traveling
      - hobby: Exploring AI and machine learning
      - hobby: Building personal tech projects
